import type { KeyboardModule } from "../kbd";

export const DvorakKeyboard: KeyboardModule = {
    name: 'Dvorak',
    layered: false,
    mapping: {
        'q': '\'',
        'w': ',',
        'e': '.',
        'r': 'p',
        't': 'y',
        'y': 'f',
        'u': 'g',
        'i': 'c',
        'o': 'r',
        'p': 'l',
        'a': 'a',
        's': 'o',
        'd': 'e',
        'f': 'u',
        'g': 'i',
        'h': 'd',
        'j': 'h',
        'k': 't',
        'l': 'n',
        ';': 's',
        ':': 'S',
        '\'': '-',
        '\"': '_',
        'z': ';',
        'x': 'q',
        'c': 'j',
        'v': 'k',
        'b': 'x',
        'n': 'b',
        'm': 'm',
        ',': 'w',
        '<': 'W',
        '.': 'v',
        '>': 'V',
        '/': 'z',
        '?': 'Z',
    },
};